services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log.level=WARN"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # for HTTP/3 UDP traffic
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.phpqa.ru`) || Host(`traefik.web3main.pro`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_AUTH}"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"

  external-ws-proxy:
    image: nginxinc/nginx-unprivileged:stable-alpine
    expose:
      - "80"
    networks:
      - app-network
    volumes:
      - ./.docker/go-chat/proxy.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ws-phpqa.rule=HostSNI(`ws.phpqa.ru`) || HostSNI(`ws.web3main.pro`)"
      - "traefik.tcp.routers.ws-phpqa.entrypoints=websecure"
      - "traefik.tcp.routers.ws-phpqa.tls=true"
      - "traefik.tcp.routers.ws-phpqa.tls.certresolver=myresolver"
      - "traefik.tcp.routers.ws-phpqa.service=ws-phpqa-service"
      - "traefik.tcp.services.ws-phpqa-service.loadbalancer.server.port=80"

  laravel:
    command: php artisan octane:frankenphp --host=0.0.0.0 --port=80 --max-requests=1000 --workers=4
    profiles:
      - legacy
    volumes:
      - ./app-laravel/php/conf.d/opcache.prod.ini:/usr/local/etc/php/conf.d/opcache.prod.ini:ro
    labels:
      - "traefik.enable=false"

    networks:
      - app-network

  pets-app:
    volumes:
      - /var/www/pets.phpqa.ru/app:/app:rw
    labels:
      - "traefik.enable=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.pets-http.rule=Host(`pets.phpqa.ru`) || Host(`pets.web3main.pro`)"
      - "traefik.http.routers.pets-http.entrypoints=web"
      #      - "traefik.http.routers.pets-http.middlewares=pets-https-redirect"
      #      - "traefik.http.middlewares.pets-https-redirect.redirectscheme.scheme=https"
      # HTTPS configuration
      - "traefik.http.routers.pets-secure.rule=Host(`pets.phpqa.ru`) || Host(`pets.web3main.pro`)"
      - "traefik.http.routers.pets-secure.entrypoints=websecure"
      - "traefik.http.routers.pets-secure.tls=true"
      - "traefik.http.routers.pets-secure.tls.certresolver=myresolver"
      - "traefik.http.services.pets.loadbalancer.server.port=80"
    networks:
      - app-network

  sveltewar-app:
    build:
      context: /var/www/sveltewar.phpqa.ru/html/
      dockerfile: Dockerfile
    volumes:
      - /var/www/sveltewar.phpqa.ru/html/public:/usr/share/nginx/html/:rw
    labels:
      - "traefik.enable=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.sveltewar-http.rule=Host(`sveltewar.phpqa.ru`) || Host(`sveltewar.web3main.pro`)"
      - "traefik.http.routers.sveltewar-http.entrypoints=web"
      #      - "traefik.http.routers.sveltewar-http.middlewares=sveltewar-https-redirect"
      #      - "traefik.http.middlewares.sveltewar-https-redirect.redirectscheme.scheme=https"
      # HTTPS configuration
      - "traefik.http.routers.sveltewar-secure.rule=Host(`sveltewar.phpqa.ru`) || Host(`sveltewar.web3main.pro`)"
      - "traefik.http.routers.sveltewar-secure.entrypoints=websecure"
      - "traefik.http.routers.sveltewar-secure.tls=true"
      - "traefik.http.routers.sveltewar-secure.tls.certresolver=myresolver"
      - "traefik.http.services.sveltewar.loadbalancer.server.port=80"
    networks:
      - app-network

  symfony:
    image: 45.9.73.190:5000/phpqa-api:latest
    #build:
    #  target: prod
    volumes:
      - ./api-symfony/php/conf.d/opcache.prod.ini:/usr/local/etc/php/conf.d/opcache.prod.ini:ro
    labels:
      - "traefik.enable=true"

      # Middleware: redirect from phpqa.ru to web3main.pro (301 permanent)
      - "traefik.http.middlewares.redirect-old-domain.redirectregex.regex=^https?://phpqa\\.ru/(.*)"
      - "traefik.http.middlewares.redirect-old-domain.redirectregex.replacement=https://web3main.pro/$${1}"
      - "traefik.http.middlewares.redirect-old-domain.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-old-domain-www.redirectregex.regex=^https?://www\\.phpqa\\.ru/(.*)"
      - "traefik.http.middlewares.redirect-old-domain-www.redirectregex.replacement=https://www.web3main.pro/$${1}"
      - "traefik.http.middlewares.redirect-old-domain-www.redirectregex.permanent=true"

      # HTTP
      - "traefik.http.routers.symfony-http.rule=Host(`phpqa.ru`) || Host(`www.phpqa.ru`) || Host(`web3main.pro`) || Host(`www.web3main.pro`)"
      - "traefik.http.routers.symfony-http.entrypoints=web"
      - "traefik.http.routers.symfony-http.service=symfony"
      - "traefik.http.routers.symfony-http.middlewares=redirect-old-domain,redirect-old-domain-www"

      # HTTPS
      - "traefik.http.routers.symfony.rule=Host(`phpqa.ru`) || Host(`www.phpqa.ru`) || Host(`web3main.pro`) || Host(`www.web3main.pro`)"
      - "traefik.http.routers.symfony.entrypoints=websecure"
      - "traefik.http.routers.symfony.tls.certresolver=myresolver"
      - "traefik.http.routers.symfony.middlewares=redirect-old-domain,redirect-old-domain-www"

      - "traefik.http.routers.symfony.service=symfony"
      - "traefik.http.services.symfony.loadbalancer.server.port=80"
